### ISSUE TITLE
F*** it

### ISSUE THREAD

**Issue by hello-smile6** [JaydenDev/searchocean#4]
Bye.

**Comment by jdev082** [comment]
@hello-smile6 Sorry, we don't support msedge users. Please use a non garbage browser that uses modern standards.

**Comment by jdev082** [comment]
font awesome icons aren't even used anymore...

**Comment by hello-smile6** [comment]
> @hello-smile6 Sorry, we don't support msedge users. Please use a non garbage browser that uses modern standards.

Um, sorry. Chromium has a large enough userbase, you should support it.

**Comment by jdev082** [comment]
@hello-smile6 its an edge problem

**Comment by jdev082** [comment]
@hello-smile6 also font-awesome icons aren't even used

**Comment by hello-smile6** [comment]
> font awesome icons aren't even used anymore...

Oh, I didn't notice. Also, it's not specific to Chromium. You used the `fas` class instead of `fa`.

**Comment by jdev082** [comment]
fontawesome specifically says to use fas. please research before making random accusations.

**Comment by jdev082** [comment]
also it worked for me.. soo.

**Comment by hello-smile6** [comment]
> fontawesome specifically says to use fas. please research before making random accusations.

That's for the `solid` icons. They make people pay to use them.

**Comment by jdev082** [comment]
@hello-smile6 you know font awesome icons aren't used anymore... right?

**Comment by hello-smile6** [comment]
> @hello-smile6 you know font awesome icons aren't used anymore... right?

Yes, I was just telling you!

**Comment by jdev082** [comment]
https://github.com/JaydenDev/searchocean-app

**Comment by jdev082** [comment]
solved
